### ISSUE TITLE
Optimizer may take items from the factory output containers

### ISSUE THREAD

**Issue by lgfrbcsgo** [lgfrbcsgo/du-factory-generator#1]
If the factory is supposed to produce steel and basic screws, the optimizer will take steel from the factory output containers to produce basic screws. This results in less steel being produced than specified by the user.

**Comment by tvwenger** [comment]
Should be easy to fix by adding something like a "UserNode" that draws the requested rate from the factory output containers. Then the algorithm will take that into consideration when computing the container egress.
