### ISSUE TITLE
Add support for recipes which need more than 7 different ingredient

### ISSUE THREAD

**Issue by lgfrbcsgo** [lgfrbcsgo/du-factory-generator#5]
Currently, every container contains only one kind of item and its byproducts. In case of a recipe with 8 or more ingredients, the optimizer would connect the machine to more than 7 containers.

One could either amalgamate containers or add transfer units. 

Care has to be taken when amalgamating containers as this could starve machines under certain conditions. If a machine can take an ingredient from either of 2 containers, it will take it from the container which was connected to the machine first.

**Comment by tvwenger** [comment]
I think transfer units are the way to go here.
