### ISSUE TITLE
"Container egress exceeds ingress" error when creating new factory

### ISSUE THREAD

**Issue by jammaau** [lgfrbcsgo/du-factory-generator#66]
When I click next on Select production quantity step I get the error Container egress exceeds ingress

![image](https://user-images.githubusercontent.com/72777499/101262088-07c37380-3790-11eb-9bfb-91ab2fc16276.png)

**Comment by tvwenger** [comment]
Thanks for reporting! I confirmed the bug. We'll get a fix pushed ASAP.

**Comment by tvwenger** [comment]
Fixed @jammaau Thanks again for reporting!
