### ISSUE TITLE
Byproduct Links are Duplicated

### ISSUE THREAD

**Issue by MrJulsen** [lgfrbcsgo/du-factory-generator#68]
When planning just a refining factory the last output links doubles the last by-product links.

**Comment by tvwenger** [comment]
Thanks for reporting! I've confirmed this bug. In fact, it happens in all factories: the byproduct links show up at the end of the regular link outputs (solid arrow) in addition to the byproduct link outputs (dashed arrow).

**Comment by tvwenger** [comment]
Fixed in version 3
