### ISSUE TITLE
Add schematics

### ISSUE THREAD

**Issue by MrJulsen** [lgfrbcsgo/du-factory-generator#69]
Add schematics and their quanta prices to parts list.

**Comment by tvwenger** [comment]
Thanks for the suggestion! At present, we can't build schematics. It might be interesting to present to the user a total price to buy the schematics for all industries.

**Comment by MrJulsen** [comment]
The last sentence is what i meant anyway. And the count of each schematic you would need to buy.
Sorry for not being clear in the beginning.

**Comment by McSon2** [comment]
Maybe  new recipes too. Like uncommon  Industry and container XL

**Comment by tvwenger** [comment]
Implemented in Version 3
