### ISSUE TITLE
Gas Container Exceeds Link Limit

### ISSUE THREAD

**Issue by tvwenger** [lgfrbcsgo/du-factory-generator#77]
For example, have a factory produce all fuels except "warp cells".

**Comment by Vengeance1989** [comment]
Update is currently in progress of the whole system bare with us :)

**Comment by tvwenger** [comment]
@Vengeance1989 hehe yes I know, I'm the one working on it ;)

**Comment by tvwenger** [comment]
Fixed in version 3
