### ISSUE TITLE
Factory Error

### ISSUE THREAD

**Issue by DrangPo** [lgfrbcsgo/du-factory-generator#86]
Received the following error when I went to create a new factory for Transfer Units.

<img width="505" alt="factory error 1" src="https://user-images.githubusercontent.com/6303128/113463774-c4df7880-93dc-11eb-9acd-8d0d441832e7.png">

<img width="627" alt="factory error 2" src="https://user-images.githubusercontent.com/6303128/113463778-cf017700-93dc-11eb-803a-9f20a3171917.png">

<img width="745" alt="Factory Error" src="https://user-images.githubusercontent.com/6303128/113463784-d6288500-93dc-11eb-8e5e-5fb41277bda1.png">

Did these steps a few times and always get the same error.   where as I was able to create a new factory for warp cells.. so it's not my end.

**Comment by tvwenger** [comment]
Confirmed! Thanks for the report.

**Comment by tvwenger** [comment]
Fixed! Was an error in the recipes. I just pushed the fix to master, and now I'll update the website to v3.1. Thanks!
