### ISSUE TITLE
T1 scrap

### ISSUE THREAD

**Issue by Istarian** [lgfrbcsgo/du-factory-generator#87]
Just crashes on silicon, iron, or aluminium scrap

**Comment by tvwenger** [comment]
Confirmed! Thanks for reporting.

**Comment by tvwenger** [comment]
Fixed in https://github.com/lgfrbcsgo/du-factory-generator/pull/88/commits/c927d58239ee113134050e970f6739d067e37921 Will merge into master and update website soon
