### ISSUE TITLE
Correction of missing recipes for atmo and space engine Pr request

### ISSUE THREAD

**Issue by Dunkh4n** [lgfrbcsgo/du-factory-generator#94]
Hi,

I have corrected and added the missing/wrong recipes for atmo and space engine, and typos for MIlitary -> Military as cited in the issues #91 
There was in fact several error or missing recipes.
I've tested it locally and everything works fine, at least in my end.
I made a pr request, where you can check what i did.

**Comment by tvwenger** [comment]
Fixed by https://github.com/lgfrbcsgo/du-factory-generator/pull/95
